### ISSUE TITLE
 Interface Zoom tools

### ISSUE THREAD

**Issue by Dominus77** [GHopperMSK/svgMap#3]
Привет!
https://github.com/GHopperMSK/svgMap/blob/cc460dcd91b3c8df768b2b708bae2ecffe05c0ae/views/default.php#L27-L31
Этот вариант буден не лучше?
```
<?php
/* @var $id string */

$this->registerCss("
    .svg_map_zoom_tools {
        position: absolute;
        bottom:0;
        z-index:1;
        list-style: none;
        padding:0;
    }
    .svg_map_zoom_tools li {
        display:inline;
        cursor: pointer;
    }
");
?>

<ul id="tools_<?= $id ?>" class="svg_map_zoom_tools">
    <li><i class="glyphicon glyphicon-zoom-in" aria-hidden="true"></i></li>
    <li><i class="glyphicon glyphicon-refresh" aria-hidden="true"></i></li>
    <li><i class="glyphicon glyphicon-zoom-out" aria-hidden="true"></i></li>
</ul>
```
Иконки встроенные, не нужно подключать сторонние FontAwesome.
Demo: http://www.picshare.ru/view/8389031/

**Comment by np25071984** [comment]
Привет. Я как раз думаю, как бы избежать зависимости от fontawesome. Да, этот вариант безусловно лучше. Только refresh вопросы вызывает.
P.S. Тебя не смущает, что у тебя карта вврех ногами рисуется? )

**Comment by Dominus77** [comment]
Верх ногами? Что то не обращал внимания, я думаю это от данных зависит.
Какие данные такой и рисунок))

**Comment by np25071984** [comment]
Я тоже так думал, но жизнь не перестает удивлять.
У меня в js есть код:
```
// TODO: why svg is turned upside down?!
svg.setAttribute('transform', 'scale(1, -1)');
```
Там вся магия.

**Comment by Dominus77** [comment]
да, и этот код напрочь убивает работу виджета в ФФ))

**Comment by Dominus77** [comment]
я гляну почему так происходит, имею ввиду переворот
https://github.com/GHopperMSK/svgMap/issues/4
