### ISSUE TITLE
Демо данные

### ISSUE THREAD

**Issue by Dominus77** [GHopperMSK/svgMap#4]
Разобрался я с переворотом карты, дело как и [говорил](https://github.com/GHopperMSK/svgMap/issues/3#issuecomment-351649000), в данных.
Распарсил новые данные, подключил и всё ОК!
Demo: http://www.picshare.ru/view/8389267/

Новые данные можно забрать тут:
https://github.com/Dominus77/svgMap/tree/master/example
1. russia.json
2. world.json

Использование:
```
$file = Yii::getAlias('@ghopper/svgmap/example') . "/russia.json";
$data = file_get_contents($file);
$states = json_decode($data);
```

**Comment by np25071984** [comment]
Круто! Ты не мог бы запушить их мне? А то файлы скопировать нельзя, а копипастить лениво... Да и вдруг что поправишь.

**Comment by Dominus77** [comment]
Запулил: https://github.com/GHopperMSK/svgMap/pull/6
